# Generated by Django 6.0.5 on 2026-05-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='movement_category',
            field=models.CharField(choices=[('venta', 'Venta Directa'), ('gasto', 'Gasto Operativo'), ('nomina', 'Pago de Nómina'), ('proveedor', 'Pago a Proveedores'), ('ajuste', 'Ajuste de Inventario')], default='venta', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='unique_tenant_email'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='unique_tenant_sku'),
        ),
    ]
