# Generated by Django 6.0.5 on 2026-05-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_purchaseorder_purchaseitem_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('basic', 'Básico - Gratis'), ('pro', 'Pro - $499/mes'), ('enterprise', 'Enterprise - $999/mes')], default='basic', max_length=20),
        ),
    ]
