# Generated by Django 6.0.5 on 2026-05-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_tenant_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
